version: '3'
services:
    databaseserver:
        image: database-img
        container_name: databaseserver
        build:
            context: ../ShortPaper_DB
        volumes:
            - type: bind
              source: ./my.cnf
              target: /etc/my.cnf
        ports:
            - 3306:3306
        restart: always

    apiserver:
        image: api-img
        container_name: apiserver
        build:
            context: ../ShortPaper_API
        depends_on:
            - databaseserver
        links:
            - databaseserver:databaseserver
        expose:
            - 3000
        volumes:
            - /path/on/host:/app/uploads
        restart: always

    webserver:
        image: web-img
        container_name: webserver
        build:
            context: ../ShortPaper_Web
        depends_on:
            - databaseserver
            - apiserver
        expose:
            - 80
        restart: always      

    reverseproxy:
        image: nginx:1.17.10
        container_name: reverseproxyserver
        depends_on:
            - databaseserver
            - apiserver
            - webserver
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf  
            - ../cert/cp23-un1.crt:/etc/ssl/certs/cp23-un1.crt
            - ../certs/cp23-un1.key:/etc/ssl/private/cp23-un1.key
        ports:
            - 443:443    
            - 9090:80
        restart: on-failure
